title: Jazz of Japan
author: Brian McCrory
email: "&#106;&#097;&#122;&#122;&#115;&#116;&#117;&#100;&#121;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
description: >-
  Sharing the best of new jazz from Japan... in English!
baseurl: ""
url: "https://www.jazzofjapan.com"
logo: "/assets/images/J-circle.png"
google_analytics: UA-207659347-2
rss: RSS
search: "Search this site"

header_pages:
  - articles.md
  - albums.md
  - musicians.md
  - notes.md

collections:
  albums:
    sort_by: sort_value
    output: true

defaults:
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/J-circle.png"
  - scope:
      path: ""
    values:
      layout: "default"
      

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
