title: Jazz of Japan
author: Brian McCrory
email: jazzstudy@gmail.com
description: >-
  Sharing the best of new jazz from Japan... in English!
baseurl: ""
url: "https://www.jazzofjapan.com"
google_analytics: UA-207659347-2
twitter_username: jjazzstack
instagram_username: jjazzstack

header_pages:
  - articles.md
  - albums.md
  - musicians.md
  - audio.md

collections:
  albums:
    sort_by: sort_value
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
