name: Remove old artifacts 1 month

on: push

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts 1 month
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
